import {
  Globe,
  One,
  Three,
  Two,
  Four,
  Five,
  Six,
  Seven,
  Eight,
  Nine,
  Ten,
  Twleve,
  Eleven,
} from "@/app/component/svg";

export const keys = [
  [
    {
      name: "esc",
      icon: "",
      className: "w-30 justify-start items-end pb-2 pl-4 ",
    },
    { name: "F1", icon: <One />, className: "flex-col text-sm" },
    { name: "F2", icon: <Two />, className: "flex-col text-sm" },
    { name: "F3", icon: <Three />, className: "flex-col text-sm" },
    { name: "F4", icon: <Four />, className: "flex-col text-sm" },
    { name: "F5", icon: <Five />, className: "flex-col text-sm" },
    { name: "F6", icon: <Six />, className: "flex-col text-sm" },
    { name: "F7", icon: <Seven />, className: "flex-col text-sm" },
    { name: "F8", icon: <Eight />, className: "flex-col text-sm" },
    { name: "F9", icon: <Nine />, className: "flex-col text-sm" },
    { name: "F10", icon: <Ten />, className: "flex-col text-sm" },
    { name: "F11", icon: <Eleven />, className: "flex-col text-sm" },
    { name: "F12", icon: <Twleve />, className: "flex-col text-sm" },
    { name: "", icon: "", className: "flex-col " },
  ],

  [
    { name: "`", icon: "~", className: "flex-col" },
    { name: "1", icon: "!", className: "flex-col" },
    { name: "2", icon: "@", className: "flex-col" },
    { name: "3", icon: "#", className: "flex-col" },
    { name: "4", icon: "$", className: "flex-col" },
    { name: "5", icon: "%", className: "flex-col" },
    { name: "6", icon: "^", className: "flex-col" },
    { name: "7", icon: "&", className: "flex-col" },
    { name: "8", icon: "*", className: "flex-col" },
    { name: "9", icon: "(", className: "flex-col" },
    { name: "0", icon: ")", className: "flex-col" },
    { name: "-", icon: "_", className: "flex-col" },
    { name: "=", icon: "+", className: "flex-col" },
    {
      name: "delete",
      icon: "",
      className: "w-30 justify-end items-end pb-2 pr-4",
    },
  ],

  [
    {
      name: "tab",
      icon: "",
      className: "w-30 justify-start items-end pb-2 pl-4",
    },
    { name: "Q", icon: "", className: "" },
    { name: "W", icon: "", className: "" },
    { name: "E", icon: "", className: "" },
    { name: "R", icon: "", className: "" },
    { name: "T", icon: "", className: "" },
    { name: "Y", icon: "", className: "" },
    { name: "U", icon: "", className: "" },
    { name: "I", icon: "", className: "" },
    { name: "O", icon: "", className: "" },
    { name: "P", icon: "", className: "" },
    { name: "[", icon: "{", className: "flex-col" },
    { name: "]", icon: "}", className: "flex-col" },
    { name: "\\", icon: "|", className: "flex-col" },
  ],

  [
    {
      name: "caps lock",
      icon: "",
      className: "w-33 justify-start items-end pb-2 pl-4",
    },
    { name: "A", icon: "", className: "" },
    { name: "S", icon: "", className: "" },
    { name: "D", icon: "", className: "" },
    { name: "F", icon: "", className: "" },
    { name: "G", icon: "", className: "" },
    { name: "H", icon: "", className: "" },
    { name: "J", icon: "", className: "" },
    { name: "K", icon: "", className: "" },
    { name: "L", icon: "", className: "" },
    { name: ";", icon: ":", className: "flex-col" },
    { name: "'", icon: '"', className: "flex-col pt-2" },
    {
      name: "return",
      icon: "",
      className: "w-30 justify-end items-end pb-2 pr-4",
    },
  ],

  [
    {
      name: "shift",
      icon: "",
      className: "w-40 justify-start items-end pb-2 pl-4",
    },
    { name: "Z", icon: "", className: "" },
    { name: "X", icon: "", className: "" },
    { name: "C", icon: "", className: "" },
    { name: "V", icon: "", className: "" },
    { name: "B", icon: "", className: "" },
    { name: "N", icon: "", className: "" },
    { name: "M", icon: "", className: "" },
    { name: ",", icon: "<", className: "flex-col" },
    { name: ".", icon: ">", className: "flex-col" },
    { name: "/", icon: "?", className: "flex-col" },
    {
      name: "shift",
      icon: "",
      className: "w-40 justify-end items-end pb-2 pr-4",
    },
  ],

  [
    {
      name: "fn",
      icon: <Globe />,
      className: "text-sm justify-between gap-4 pb-1 items-end ",
    },
    {
      name: "control",
      icon: "^",
      className: "flex-col text-sm items-start pl-1.5  ",
    },
    {
      name: "option",
      icon: "⌥",
      className: " flex-col text-sm items-start pl-1.5 ",
    },
    {
      name: "command",
      icon: "⌘",
      className: "w-19 flex-col text-sm items-start pl-1.5 ",
    },
    { name: "", icon: "", className: "w-[23rem] " },
    {
      name: "command",
      icon: "⌘",
      className: "w-19 flex-col text-sm items-end pr-1.5 ",
    },
    {
      name: "option",
      icon: "⌥",
      className: "flex-col text-sm items-end pr-1.5 ",
    },
    { name: "Left", icon: "", className: "h-9 flex-col" },
  ],
];
