export const keys = [
  // 🔹 Row 1 — Function & Escape Keys
  [
    {
      name: "esc",
      icon: "",
      className: "w-30 justify-start items-end pb-2 pl-4",
    },
    { name: "F1", icon: "e", className: "flex-col " },
    { name: "F2", icon: "", className: "" },
    { name: "F3", icon: "", className: "" },
    { name: "F4", icon: "", className: "" },
    { name: "F5", icon: "", className: "" },
    { name: "F6", icon: "", className: "" },
    { name: "F7", icon: "", className: "" },
    { name: "F8", icon: "", className: "" },
    { name: "F9", icon: "", className: "" },
    { name: "F10", icon: "", className: "" },
    { name: "F11", icon: "", className: "" },
    { name: "F12", icon: "", className: "" },
    { name: "", icon: "", className: "" },
  ],

  // 🔹 Row 2 — Number Row
  [
    { name: "`", icon: "", className: "" },
    { name: "1", icon: "", className: "" },
    { name: "2", icon: "", className: "" },
    { name: "3", icon: "", className: "" },
    { name: "4", icon: "", className: "" },
    { name: "5", icon: "", className: "" },
    { name: "6", icon: "", className: "" },
    { name: "7", icon: "", className: "" },
    { name: "8", icon: "", className: "" },
    { name: "9", icon: "", className: "" },
    { name: "0", icon: "", className: "" },
    { name: "-", icon: "", className: "" },
    { name: "=", icon: "", className: "" },
    {
      name: "delete",
      icon: "",
      className: "w-30 justify-start items-end pb-2 pl-4",
    },
  ],

  // 🔹 Row 3 — QWERTY Row
  [
    {
      name: "tab",
      icon: "",
      className: "w-30 justify-start items-end pb-2 pl-4",
    },
    { name: "Q", icon: "", className: "" },
    { name: "W", icon: "", className: "" },
    { name: "E", icon: "", className: "" },
    { name: "R", icon: "", className: "" },
    { name: "T", icon: "", className: "" },
    { name: "Y", icon: "", className: "" },
    { name: "U", icon: "", className: "" },
    { name: "I", icon: "", className: "" },
    { name: "O", icon: "", className: "" },
    { name: "P", icon: "", className: "" },
    { name: "[", icon: "{", className: "flex-col" },
    { name: "]", icon: "}", className: "flex-col" },
    { name: "\\", icon: "|", className: "flex-col" },
  ],

  // 🔹 Row 4 — Home Row (ASDF)
  [
    { name: "Caps Lock", icon: "", className: "w-36" },
    { name: "A", icon: "", className: "" },
    { name: "S", icon: "", className: "" },
    { name: "D", icon: "", className: "" },
    { name: "F", icon: "", className: "" },
    { name: "G", icon: "", className: "" },
    { name: "H", icon: "", className: "" },
    { name: "J", icon: "", className: "" },
    { name: "K", icon: "", className: "" },
    { name: "L", icon: "", className: "" },
    { name: ";", icon: "", className: "" },
    { name: "'", icon: "", className: "" },
    { name: "Enter", icon: "", className: "w-36" },
  ],

  // 🔹 Row 5 — Bottom Row (ZXCV)
  [
    { name: "Shift", icon: "", className: "w-42" },
    { name: "Z", icon: "", className: "" },
    { name: "X", icon: "", className: "" },
    { name: "C", icon: "", className: "" },
    { name: "V", icon: "", className: "" },
    { name: "B", icon: "", className: "" },
    { name: "N", icon: "", className: "" },
    { name: "M", icon: "", className: "" },
    { name: ",", icon: "", className: "" },
    { name: ".", icon: "", className: "" },
    { name: "/", icon: "", className: "" },
    { name: "Shift", icon: "", className: "w-42" },
  ],

  // 🔹 Row 6 — Spacebar Row
  [
    { name: "Ctrl", icon: "", className: "" },
    { name: "Fn", icon: "", className: "" },
    { name: "Alt", icon: "", className: "" },
    { name: "Cmd", icon: "", className: "" },
    { name: "Space", icon: "", className: "w-[23rem]" },
    { name: "Cmd", icon: "", className: "" },
    { name: "Alt", icon: "", className: "" },
    { name: "Left", icon: "", className: "h-9 " },
    { name: "Down", icon: "", className: "h-9 " },
    { name: "Up", icon: "", className: "h-9 " },
    { name: "Right", icon: "", className: "h-9 " },
  ],
];
